<a href="https://colab.research.google.com/github/kravtsov-s-o/django-personal-assistant/blob/master/DS_HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [3]:
a = np.linspace(1, 10, num=10)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.


In [5]:
a = np.zeros((3,3), dtype=int)
print(a)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [8]:
a = np.random.randint(1, 11, (5, 5))
print(a)

[[ 6  3  3  1  1]
 [ 1  3  2  4  5]
 [ 1  8  4  9  5]
 [ 6  6  8  2  4]
 [ 8  9  1  5 10]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [11]:
a = np.random.rand(4, 4)
print(a)

[[0.25564782 0.79731126 0.31745681 0.96769961]
 [0.81131662 0.47222281 0.56027222 0.61383775]
 [0.94969867 0.59290775 0.62559189 0.085473  ]
 [0.67850852 0.98809055 0.83232878 0.35417892]]


5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [16]:
a = np.random.randint(1, 11, (5,))
b = np.random.randint(1, 11, (5,))
print(f'Array a: {a}')
print(f'Array b: {b}')
print(f'Додавання: {a + b}')
print(f'Віднімання: {a - b}')
print(f'Множення: {a * b}')

Array a: [ 7 10  4 10  2]
Array b: [5 8 3 7 1]
Додавання: [12 18  7 17  3]
Віднімання: [2 2 1 3 1]
Множення: [35 80 12 70  2]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [18]:
a = np.random.random(7)
b = np.random.random(7)
print(f'Array a: {a}')
print(f'Array b: {b}')
print(np.dot(a,b))

Array a: [0.90492496 0.63565776 0.05217353 0.03583857 0.31696014 0.99371907
 0.42446732]
Array b: [0.35068164 0.37387927 0.09400278 0.42919344 0.23302201 0.90004873
 0.63239714]
1.8119721567502964


7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [25]:
a = np.random.randint(1, 11, (2, 2))
b = np.random.randint(1, 11, (2, 3))
print(f'a: {a}')
print(f'b: {b}')
print(np.dot(a,b))

a: [[1 9]
 [5 5]]
b: [[ 6  6 10]
 [ 5  3 10]]
[[ 51  33 100]
 [ 55  45 100]]


8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [26]:
a = np.random.randint(1, 11, (3, 3))
a_inv = np.linalg.inv(a)
print(f'a: {a}')
print(f'a_inv: {a_inv}')

a: [[2 4 8]
 [7 9 5]
 [2 3 8]]
a_inv: [[-1.23913043e+00  1.73913043e-01  1.13043478e+00]
 [ 1.00000000e+00 -3.88578059e-17 -1.00000000e+00]
 [-6.52173913e-02 -4.34782609e-02  2.17391304e-01]]


9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [27]:
a = np.random.rand(4, 4)
a_inv = np.linalg.inv(a)
print(f'a: {a}')
print(f'a_inv: {a_inv}')

a: [[0.44577405 0.93197098 0.5210662  0.64304664]
 [0.49916938 0.25878735 0.08910242 0.23461349]
 [0.53290061 0.73486576 0.37983996 0.28319741]
 [0.87564301 0.67040933 0.3790644  0.42140968]]
a_inv: [[ -1.10423271   0.26705333  -0.24604247   1.70166337]
 [ -0.28831943   6.21634319   5.9269314   -7.00393673]
 [  0.16495914 -14.01032565  -5.58674872  11.3027487 ]
 [  2.60477063   2.15817977  -3.89238144  -0.18750104]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [33]:
matrix = np.random.randint(1, 11, (3, 4))
vector = np.random.randint(1,11, (4,))
print(matrix)
print(vector)
print(matrix * vector)

[[7 6 3 9]
 [9 8 8 9]
 [6 6 4 7]]
[5 8 2 3]
[[35 48  6 27]
 [45 64 16 27]
 [30 48  8 21]]


11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [32]:
matrix = np.random.rand(2,3)
vector = np.random.rand(3)
print(matrix)
print(vector)
print(matrix * vector)

[[0.80540331 0.10726369 0.42018182]
 [0.94673494 0.6412287  0.65122102]]
[0.03078399 0.74187208 0.83833796]
[[0.02479353 0.07957593 0.35225437]
 [0.02914428 0.47570967 0.5459433 ]]


12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [31]:
matrix = np.random.randint(1, 11, (2,2))
vector = np.random.randint(1,11, (2,2))
print(matrix)
print(vector)
print(matrix * vector)

[[5 2]
 [2 3]]
[[ 9  7]
 [ 5 10]]
[[45 14]
 [10 30]]


13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [34]:
matrix = np.random.randint(1, 11, (2,2))
vector = np.random.randint(1,11, (2,2))
print(matrix)
print(vector)
print(np.dot(matrix, vector))

[[10  5]
 [ 4  6]]
[[3 2]
 [8 4]]
[[70 40]
 [60 32]]


14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [37]:
a = np.random.randint(1, 101, (5, 5))
print(a)
print(a.sum())

[[ 76  57  36  47  42]
 [ 61   1   9  75  52]
 [ 38  90  63  70  66]
 [ 55  40  61  60  86]
 [100   5  15  50  33]]
1288


15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [38]:
a = np.random.randint(1, 11, (4, 4))
b = np.random.randint(1, 11, (4, 4))
print(a)
print(b)
print(a-b)

[[ 4  8  8  2]
 [ 4  2  5  1]
 [ 2  2  2  3]
 [ 1  9 10  7]]
[[10  8  8  3]
 [ 3  2  6  6]
 [ 6  8 10 10]
 [ 7  6  6  3]]
[[-6  0  0 -1]
 [ 1  0 -1 -5]
 [-4 -6 -8 -7]
 [-6  3  4  4]]


16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [40]:
a = np.random.rand(3,3)
print(a)
print(np.sum(a, axis=1, keepdims=True))

[[0.74420392 0.15924419 0.77738159]
 [0.2753838  0.3354102  0.93622457]
 [0.19332297 0.58484063 0.93916436]]
[[1.6808297 ]
 [1.54701857]
 [1.71732796]]


17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [42]:
a = np.random.randint(1, 10, (3, 4))
sq = np.square(a)
print(a)
print(sq)

[[7 3 2 2]
 [9 6 4 3]
 [8 5 6 4]]
[[49  9  4  4]
 [81 36 16  9]
 [64 25 36 16]]


18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [43]:
a = np.random.randint(1, 51, 4)
sqrt = np.sqrt(a)
print(a)
print(sqrt)

[18 27 21 44]
[4.24264069 5.19615242 4.58257569 6.63324958]
